### ISSUE TITLE
About arch compiling process

### ISSUE THREAD

**Issue by ZikZakFR** [GRAPHENE9932/ImageUpscalerQt#1]
I suppose you meant wget instead of wgen
cmake .. returns error about kineto.
I can not find a package of that name but aur contains one if it is really about Gemini (which I doubt).

**Comment by GRAPHENE9932** [comment]
Thanks for the pointer to the typo, fixed.
About kineto: for me it is just warning, but not an error.

Please give me the full cmake output

**Comment by ZikZakFR** [comment]
I got this:
CMake Warning at /usr/lib64/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /usr/lib64/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:44 (find_package)

then:

make
[  6%] Automatic MOC and UIC for target imageupscalerqt
[  6%] Built target imageupscalerqt_autogen
make[2]: ***  No rule to build target « ../res/SRCNN/3-1-9 48-24.pt », needed for « qrc_resources.cpp ». Abort.
make[1]: *** [CMakeFiles/Makefile2:83 : CMakeFiles/imageupscalerqt.dir/all] Error 2
make: *** [Makefile:136 : all] Error 2

**Comment by GRAPHENE9932** [comment]
I'm sorry, I made a very stupid mistake. I forgot to `git add .` so some files was missing in the repository on GitHub.
Fixed. Please try again from the "Configure and compile" part (remember to remove the ImageUpscalerQt folder before).

**Comment by ZikZakFR** [comment]
Good, compilation  worked.

But then FSRCNN generated a core dump. Any idea why?
Split image with a blocksize of 32.

./imageupscalerqt
QIODevice::read (QFile, ":/3-1-3-2 128-16-32.pt"): device not open
terminate called after throwing an instance of 'c10::Error'
  what():  PytorchStreamReader failed reading zip archive: not a ZIP archive
Exception raised from valid at /build/python-pytorch/src/pytorch-1.9.0/caffe2/serialize/inline_container.cc:151 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xaa (0x7f236b2bd57a in /usr/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f236b28ace7 in /usr/lib/libc10.so)
frame #2: caffe2::serialize::PyTorchStreamReader::valid(char const*, char const*) + 0x37a (0x7f23643b0cfa in /usr/lib/libtorch_cpu.so)
frame #3: caffe2::serialize::PyTorchStreamReader::init() + 0xb3 (0x7f23643b11e3 in /usr/lib/libtorch_cpu.so)
frame #4: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::shared_ptr<caffe2::serialize::ReadAdapterInterface>) + 0x97 (0x7f23643b2537 in /usr/lib/libtorch_cpu.so)
frame #5: torch::jit::load(std::shared_ptr<caffe2::serialize::ReadAdapterInterface>, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0xdc (0x7f236589dcdc in /usr/lib/libtorch_cpu.so)
frame #6: torch::jit::load(std::shared_ptr<caffe2::serialize::ReadAdapterInterface>, c10::optional<c10::Device>) + 0xb5 (0x7f236589df25 in /usr/lib/libtorch_cpu.so)
frame #7: torch::serialize::InputArchive::load_from(char const*, unsigned long, c10::optional<c10::Device>) + 0x11c (0x7f2365ca8d8c in /usr/lib/libtorch_cpu.so)
frame #8: void torch::load<char*, int, c10::DeviceType const&>(std::vector<at::Tensor, std::allocator<at::Tensor> >&, char*&&, int&&, c10::DeviceType const&) + 0x9d (0x56130e49f9e8 in ./imageupscalerqt)
frame #9: TaskFSRCNN::do_task(OpenImageIO_v2_2::ImageBuf) + 0x1c8 (0x56130e49b150 in ./imageupscalerqt)
frame #10: Worker::do_tasks(std::function<void ()>, std::function<void ()>, std::function<void (QString)>) + 0x15e (0x56130e4a5a16 in ./imageupscalerqt)
frame #11: <unknown function> + 0x84a23 (0x56130e4b6a23 in ./imageupscalerqt)
frame #12: <unknown function> + 0x8484e (0x56130e4b684e in ./imageupscalerqt)
frame #13: <unknown function> + 0x84709 (0x56130e4b6709 in ./imageupscalerqt)
frame #14: <unknown function> + 0x8466e (0x56130e4b666e in ./imageupscalerqt)
frame #15: <unknown function> + 0x84652 (0x56130e4b6652 in ./imageupscalerqt)
frame #16: <unknown function> + 0xd33c4 (0x7f23611503c4 in /usr/lib/libstdc++.so.6)
frame #17: <unknown function> + 0x9259 (0x7f2361ed2259 in /usr/lib/libpthread.so.0)
frame #18: clone + 0x43 (0x7f2360f945e3 in /usr/lib/libc.so.6)

**Comment by GRAPHENE9932** [comment]
Fixed. This software still unstable now, so wait for the new versions (1.5 or 1.6).
